feature: Agreement에 desciption 추가 구현
GIST-Petition-Site-Project/GIST-petition-server pull request #183
Opened 2022-02-08 13:08 UTC by ChoiEungi

- Comment Domain을 지웠습니다.
- N+1 문제를 해결하려 했는데 Pagable이 있어 해결하기 어렵습니다. 다음 이슈를 확인해주세요 #159 

Close #176

2022-02-08 13:26 UTC, koseyeon reviewed
몇가지 부분에 대해 리뷰남겼습니다!

2022-02-08 13:26 UTC, koseyeon commented on src/main/java/com/gistpetition/api/petition/dto/AgreementResponse.java
> +    public static List<AgreementResponse> listOf(List<Agreement> agreements) {
listOf메소드를 static으로 설정한 이유가 궁금합니다

2022-02-08 13:26 UTC, koseyeon commented on src/test/java/com/gistpetition/api/petition/PetitionServiceTest.java
> +        User user2 = userRepository.save(new User("user2@email.com", "password", UserRole.USER));
바로 레포지토리에 save하는 코드에서도 gist메일형식을 가진 유저를 넣으면 어떨까요?

2022-02-08 13:55 UTC, wannte requested changes
빠르게 진행해주셨네요 :+1:
몇 가지 리뷰 남겼습니다! 확인부탁드려요!

2022-02-08 13:55 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/presentation/PetitionController.java
> +    public ResponseEntity<List<AgreementResponse>> getAllOfAgreements(@PathVariable Long petitionId) {
이 부분도 Pagination이 적용되야 할 것 같습니다!

만약 10만 건의 동의가 있다고 했을 때, heap메모리가 바로 터질것 같습니다. 수정을 하게 되었을 때, 메소드의 명도 수정했으면 좋겠습니다!

2022-02-08 13:55 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/application/PetitionService.java
> +    public Boolean agree(AgreementRequest request, Long petitionId,  Long userId) {
기존에 작성됬던 코드이긴 하지만 리턴값을 Boolean이 좋은 구현인지에 대해 의문이 드네요!

기존에는 Exception을 핸들링하는 방식이 아니여서 이 방식으로 구현한것으로 기억하는데, Exception이 도입된 지금에는 void로 처리를 해도 좋을 것 같다는 생각입니다! 다른 분들의 생각도 듣고 싶습니다.

2022-02-08 13:55 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/domain/AgreementRepository.java
> +import java.util.List;
사용하지 않는 것 같네요!

2022-02-08 13:55 UTC, wannte commented on src/test/java/com/gistpetition/api/petition/PetitionServiceTest.java
> +        Long petitionId = Long.MAX_VALUE;
notExistingPetitionId 같은 방식으로 명시적으로 나타내줄 수도 있을 것 같아요!

2022-02-08 13:55 UTC, wannte commented on src/test/java/com/gistpetition/api/petition/PetitionServiceTest.java
> +        User user2 = userRepository.save(new User("user2@email.com", "password", UserRole.USER));
동의합니다!

2022-02-08 13:55 UTC, wannte commented on src/test/java/com/gistpetition/api/petition/PetitionTest.java
> +    private static final AgreementRequest AGREEMENT_REQUEST = new AgreementRequest("동의합니다.");
AgreementRequest가 아닌 content만을 static field로 두어도 좋을 것 같습니다!

요청을 받는 dto가 domain layer의 테스트에 등장하는 것이 조금 어색하다는 생각입니다!

2022-02-09 01:49 UTC, ChoiEungi commented on src/main/java/com/gistpetition/api/petition/dto/AgreementResponse.java
> +    public static List<AgreementResponse> listOf(List<Agreement> agreements) {
`getAllOfAgreements` 메서드에서 AgreementResponse의 인스턴스 생성 없이 List<Agreement>를  List<AgreementResponse>로 변경하고 싶어서 static으로 메서드를 생성했습니다!

2022-02-09 05:47 UTC, GuruneLee commented on src/main/java/com/gistpetition/api/petition/application/PetitionService.java
> +    public Boolean agree(AgreementRequest request, Long petitionId,  Long userId) {
동의합니다

2022-02-09 06:54 UTC, ChoiEungi commented
PR 리뷰 반영하면서 크게 반영된 내용으로는

1. Petition과 Agreement를 양방향으로 변경
Agreement를 AgreementRepository에서 Page로 받아오기 위해서는 Petition field가 추가돼야 합니다. 다행히 Agreement를 생성하는 의존성이 크지 않아 코드의 큰 변경 없이 field를 추가할 수 있었습니다.

2. BatchSize를 이용한 N+1 문제 해결
BatchSize를 Default를 10으로 두어 10개 이하를 조회할 때 where in 절로 조회를, 10개가 넘어갈 때는 (조회 항목 개수/10)의 횟수만큼 조회가 이뤄진 후에 where in 절로 조회가 진행됩니다. N+1 문제에 Pagination을 적용하기 위해서는 QueryDSL을 사용해 OFFSET과 LIMIT을 정해주는 것이 가장 좋은 방법인 것 같습니다. 이 부분에 대해서는 블로그로 정리해 올리겠습니다.

Close #159

2022-02-09 06:54 UTC, ChoiEungi commented
> PR 리뷰 반영하면서 크게 반영된 내용으로는
> 
> 1. Petition과 Agreement를 양방향으로 변경
>    Agreement를 AgreementRepository에서 Page로 받아오기 위해서는 Petition field가 추가돼야 합니다. 다행히 Agreement를 생성하는 의존성이 크지 않아 코드의 큰 변경 없이 field를 추가할 수 있었습니다.
> 2. BatchSize를 이용한 N+1 문제 해결
>    BatchSize를 Default를 10으로 두어 10개 이하를 조회할 때 where in 절로 조회를, 10개가 넘어갈 때는 (조회 항목 개수/10)의 횟수만큼 조회가 이뤄진 후에 where in 절로 조회가 진행됩니다. N+1 문제에 Pagination을 적용하기 위해서는 QueryDSL을 사용해 OFFSET과 LIMIT을 정해주는 것이 가장 좋은 방법인 것 같습니다. 이 부분에 대해서는 블로그로 정리해 올리겠습니다.
> 
> Close #159

2022-02-10 09:14 UTC, wannte reviewed
몇 가지 간단한 커멘트를 남겨봤습니다!

2022-02-10 09:14 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/presentation/PetitionController.java
> +                                                                      @PathVariable Long petitionId) {
```suggestion
    public ResponseEntity<Page<AgreementResponse>> retrieveAgreements(@PathVariable Long petitionId,
                                                                      @PageableDefault(sort = "createdAt", direction = Sort.Direction.DESC) Pageable pageable) {
```
기존의 구현했던 방식과 통일성을 가져가면 좋겠다는 생각!

Pageable이 함수 시그니쳐에 들어나기 때문에, 명시적으로 메소드명으로 적어주지 않아도 될 것 같다는 생각이에요!
List를 메소드명에 명시하지 않는 개념과 비슷한 느낌입니다!

2022-02-10 09:14 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/domain/Petition.java
> +    @BatchSize(size = 10)
BatchSize를 10으로 둔 이유가 궁금하네요 ❓

2022-02-10 09:14 UTC, wannte commented on src/test/java/com/gistpetition/api/petition/PetitionServiceTest.java
> +        petitionPreviewResponses.forEach(s -> System.out.println("id: "+ s.getId() + "\n" + s.getTitle() + s.getAgreements()));
print를 한다는 것은, 직접 눈으로 검증을 진행해야할 것 같은데요!

이를 junit을 통해 진행하는 방법으로 수정해봐도 좋을 것 같아요!

BatchSize 10으로 했을 때 한 번의 쿼리로 나가는 지도 직접 테스트로 확인할 수 있으면 좋겠네요! (이 부분은 같이 이야기해봐요!)

2022-02-10 10:38 UTC, ChoiEungi commented on src/main/java/com/gistpetition/api/petition/domain/Petition.java
> +    @BatchSize(size = 10)
이 부분은 임의로 설정한지라 정책적으로 논의를 진행해보면 좋을 것 같습니다!

2022-02-10 10:39 UTC, ChoiEungi commented on src/test/java/com/gistpetition/api/petition/PetitionServiceTest.java
> +        petitionPreviewResponses.forEach(s -> System.out.println("id: "+ s.getId() + "\n" + s.getTitle() + s.getAgreements()));
앗 이 부분도 혼자 테스트 할 때 사용하고 지우지 못했네요 반영하도록 하겠습니다

2022-02-11 11:16 UTC, koseyeon reviewed
필드명 관련해서 리뷰 하나 남겼습니다!

2022-02-11 11:16 UTC, koseyeon commented on src/main/java/com/gistpetition/api/petition/dto/AgreementRequest.java
>      private String content;
```suggestion
    private String description;
```
DTO의 필드명과 Entitiy의 필드명을 같게 해주면 어떨까요?

2022-02-11 12:32 UTC, wannte approved these changes
수고했습니다! 👍

2022-02-11 12:36 UTC, wannte reviewed
요거 하나 추가로 확인 부탁해요!

2022-02-11 12:36 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/dto/AgreementResponse.java
> +
Agreement의 id도 함께 넣어서 보내주는 건 어떨까요?

프론트 측에서 식별자를 가지고 있는 게 더 좋을 것 같다는 생각이 드네요!

2022-02-11 12:39 UTC, koseyeon approved these changes

2022-02-11 12:41 UTC, merged