feat: 사전 동의 기능 구현
GIST-Petition-Site-Project/GIST-petition-server pull request #205
Opened 2022-02-12 15:10 UTC by koseyeon

기존 Petition 도메인에 
AgreeCount 필드를 추가해서 동의의 갯수를 저장해두도록 하고,
exposed 필드를 추가해서 해당 petition이 사용자에게 노출이 되어도 된다면 exposed를  true로 변경하도록 하고,
UUID 필드를 추가해서 해당 petition에 임의의 다른 사용자들이 접근할수 없도록 하는 로직을 구현했습니다.

만약 이 구현방식을 사용한다면 이에 대한 테스트도 더 추가해야 하는 상태입니다.

2022-02-13 03:16 UTC, GuruneLee reviewed
선 리뷰 남깁니다

2022-02-13 03:16 UTC, GuruneLee commented on src/main/java/com/gistpetition/api/petition/domain/Petition.java
> +    private Long agreeCount = 0L;
생성자로 안넣고, 필드에서 직접 초기화 한 이유가 있을까요?

어떤 생성자를 쓰더라도 0으로 초기화 되기 때문에 이것만 직접 초기화 한건가요?

2022-02-13 03:16 UTC, GuruneLee commented on src/test/java/com/gistpetition/api/petition/PetitionServiceTest.java
> +        User user1 = userRepository.save(new User("user1@gist.ac.kr", "pwd", UserRole.USER));
```suggestion
for (int i=0; i<Petition.REQUIRED_AGREEMENT_NUM; i++) {
        users.add(userRepository.save(new User(String.format("user%s@gist.ac.kr", i), "pwd", UserRole.USER)));
}
```

이렇게, REQUIRED_AGREEMENT_NUM 에 의존적인 테스트로 만드는게 어떨까요? 저 숫자가 바뀌면 테스트를 다시 짜야할 것 같네요

2022-02-13 03:18 UTC, GuruneLee commented
UUID를 쓰는 방식은 좋네요.
다만, TempPetition을 따로 만든다고 논의 했던거 같은데,
왜 exposed 를 추가해서 그대로 관리하기로 결정했는지 궁금합니다.

2022-02-13 07:06 UTC, wannte requested changes
쉽지 않은 부분인데, 잘 구현해주셨네요!

여러가지 고민을 많이 한 포인트들이 느껴지는 코드였습니다!

정책적인 부분이 많이 포함되어 있어서, 추후에 같이 이야기 해봤으면 좋겠습니다.

리뷰 몇 가지 남긴 부분 확인 부탁드려요!

2022-02-13 07:06 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/presentation/PetitionController.java
> +    }
TempPetitions의 명명이 조금 모호하다는 생각이 들어요!

청원의 갯수가 5개인 경우를 조회하는 비지니스 로직이라고 생각이되는데요, 지금의 경우에는 임시 청원 전체를 조회하는 api로 오인할 수 있을 것 같습니다!

마땅히 짧게 떠오르는 단어가 없지만, 길더라도 그 의미가 명확하게 들어나는게 좋다는 의견입니다. 제가 생각하는 몇 가지를 남겨보겠습니다!

`@GetMapping("/petitions/toCheck")` // 체크를 해야할 petitions 목록을 가져온다.
`@GetMapping("/petitions/waiting")` // 대기중인 petitions 목록을 가져온다. (이것도 조금 모호하긴 합니다)
`@GetMapping("/petitions/waitingForCheck")`

메소드 명도 몇 가지 적어보겠습니다.
`retrievePetitionsNeededToCheck` 
`retrievePetitionsWaitingForCheck` 
`retrievePriorConsentCompletedPetitions`

물론 이 부분은 정답이 없지만, 우리 팀적으로 동의하고 헷갈리지 않는다면 어떤 방법도 모두 좋습니다!

2022-02-13 07:06 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/presentation/PetitionController.java
> +    }
`GetMapping`을 사용하는 것이 조금 어색하다는 생각이 듭니다!

Petition의 상태를 수정하는 요청이기 때문에 다른 종류의 HTTP Method를 사용하는 것은 어떨까요?


한 가지 질문을 남기자면, 아래의 api를 통해 expose의 상태를 변경하는 방법도 있을 것 같은데요, 이렇게 분리했을 때와는 각각 어떤 장단점을 가지고 있을 지 의견을 듣고 싶습니다!
```java
   @ManagerPermissionRequired
    @PutMapping("/petitions/{petitionId}")
    public ResponseEntity<Void> updatePetition(@PathVariable Long petitionId,
                                               @Validated @RequestBody PetitionRequest changeRequest) {
        petitionService.updatePetition(petitionId, changeRequest);
        return ResponseEntity.noContent().build();
    }
 ```
 
 ---
 
 비지니스 적으로 더 고민해야 할 부분이라 생각해서 남겨봅니다! 이 부분은 추후에 같이 이야기 나눠봐요!
 
매니저가 petition 수정 api-> expose api 순차적으로 진행할지, 아니면 이 두가지를 하나의 api로 진행할지도 고민해 봐야할 것 같습니다!

2022-02-13 07:06 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/presentation/PetitionController.java
> -        return ResponseEntity.ok().body(petitionService.retrievePetitionById(petitionId));
이후에는 매니저나 어드민 권한으로 이 조회를 하는 일은 없을 까요?

2022-02-13 07:06 UTC, wannte commented on src/test/java/com/gistpetition/api/petition/PetitionServiceTest.java
> +        User user1 = userRepository.save(new User("user1@gist.ac.kr", "pwd", UserRole.USER));
좋은 방법 같습니다!
agree도 같은 방법으로 해결해볼 수 있을 것 같아요!

2022-02-13 07:06 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/domain/Petition.java
> +    private final UUID uuid = UUID.randomUUID();
Primary key를 UUID를 두는 방법과는 어떤 차이가 있을지 의견을 듣고 싶습니다!

2022-02-13 07:07 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/domain/Petition.java
> +    private final UUID uuid = UUID.randomUUID();
이렇게 UUID를 두는 아이디어 너무 좋은 것 같습니다 👍

2022-02-13 14:58 UTC, koseyeon commented on src/main/java/com/gistpetition/api/petition/domain/Petition.java
> +    private Long agreeCount = 0L;
넵 태완이형이 작성해주신 부분인데 제가 이해하기로는 그런 것 같습니다ㅎㅎ

2022-02-13 14:58 UTC, koseyeon commented on src/test/java/com/gistpetition/api/petition/PetitionServiceTest.java
> +        User user1 = userRepository.save(new User("user1@gist.ac.kr", "pwd", UserRole.USER));
동의합니다!

2022-02-13 15:24 UTC, koseyeon commented on src/main/java/com/gistpetition/api/petition/domain/Petition.java
> +    private final UUID uuid = UUID.randomUUID();
아 처음에는 primary key로 UUID를 두려고 했는데 좀 더 알아보니
다음과 같은 부분에서 문제점이 있었습니다.

대부분의 Database시스템은 PK에 자동으로 index를 적용하여 관리합니다.
따라서 UUID가 PK가 될 경우, UUID에 index가 적용되게 되는데, 
저희가 필요한 UUID는 다른 사용자가 임의로 추측해서 접근할 수 없도록 random한 값을 가지는 UUID 이므로 
index가 적용된다면 엄청난 손해가 되게 됩니다.

따라서 저는 PK는 그대로 long으로 두고, 칼럼으로 UUID를 추가해서 사용하는 방식을 선택했습니다.

2022-02-13 15:47 UTC, koseyeon commented on src/main/java/com/gistpetition/api/petition/presentation/PetitionController.java
> +    }
아 처음에 check로 했다가 temp로 바꾸었는데 ㅋㅋ
waitingForCheck 좋은것 같습니다!!

2022-02-14 01:18 UTC, GuruneLee commented on src/main/java/com/gistpetition/api/petition/domain/Petition.java
> +    private final UUID uuid = UUID.randomUUID();
랜덤한 값이 인덱스를 적용하는데 왜 손해가 되나요?

2022-02-14 03:10 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/domain/Petition.java
> +    private final UUID uuid = UUID.randomUUID();
https://devs0n.tistory.com/39
요거 한번 봐봐도 좋을 것 같아요!

2022-02-14 03:56 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/domain/Petition.java
> +    private Long agreeCount = 0L;
무조건 적으로 0으로 초기화 하는 경우에는 필드에 직접 적어주는 것도 좋은 것 같아서 위와 같이 작성했던 것 같아요!

이 부분에 대해서는 명확한 기준이 따로 있는 것은 아니라 같이 이야기 해봐도 좋을 것 같습니다!

2022-02-15 02:25 UTC, ChoiEungi commented on src/main/java/com/gistpetition/api/petition/presentation/PetitionController.java
> +    }
/petition/preview 는 어떤가요?!

2022-02-15 03:30 UTC, koseyeon commented on src/main/java/com/gistpetition/api/petition/presentation/PetitionController.java
> +    }
preview는 제가 느끼기로는 일반 사용자에게 보여주기 위한 api같은 느낌이 드는거 같아요!

2022-02-15 03:46 UTC, koseyeon commented on src/main/java/com/gistpetition/api/petition/presentation/PetitionController.java
> +    }
PUT으로 했어야 하는데 잘못했네요 감사합니다!

그리고 저는 기존 updatePetition 메소드를 활용하는 것보다, 따로 expose 메소드를 두는게 더 효율적일 수 있다고 생각합니다.
이유는 petition의 내용,제목 등을 업데이트하지 않고 expose승인만 하는 경우에는 
exposePetition API를 이용하는 것이 Petition의 내용, 제목 등이 변경되었는지 아닌지 검증할 필요가 없고, 
expose 필드값만 변경해주면 되기 때문에 더 효율적이기 때문입니다.

2022-02-15 03:48 UTC, koseyeon commented on src/main/java/com/gistpetition/api/petition/presentation/PetitionController.java
> -        return ResponseEntity.ok().body(petitionService.retrievePetitionById(petitionId));
uuid가 아닌 id로 조회하는 api는 매니저나 어드민용으로 활용하면 좋을 것 같습니다!

2022-02-15 12:37 UTC, wannte approved these changes
까다로운 기능인데, 잘 구현해주셨네요!

수고했습니다!

2022-02-15 12:49 UTC, merged