feat: 만료된 청원 조회 기능 구현
GIST-Petition-Site-Project/GIST-petition-server pull request #236
Opened 2022-02-19 12:34 UTC by koseyeon

사용자에게 보여지는 청원을 진행중인 청원/ 만료된 청원으로 구분하도록 하였습니다.
/petitions로 접근하면 진행중인 청원들이,
/petitions/expired로 접근하면 만료된 청원들이 조회됩니다.

진행중인 청원과 만료된 청원 모두 카테고리 별 조회가 가능하도록 했습니다.

2022-02-19 13:01 UTC, wannte requested changes

2022-02-19 13:01 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/application/PetitionService.java
> +    public Page<PetitionPreviewResponse> retrieveReleasedAndNotExpiredPetition(Pageable pageable) {
```suggestion
    public Page<PetitionPreviewResponse> retrieveOngoingPetition(Pageable pageable) {
```

진행중인 청원이라는 비지니스적인 메시지를 던지면 좋을 것 같아요!

2022-02-19 13:01 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/application/PetitionService.java
> +    public Page<PetitionPreviewResponse> retrieveReleasedAndExpiredPetition(Pageable pageable) {
```suggestion
    public Page<PetitionPreviewResponse> retrieveExpiredPetition(Pageable pageable) {
```
여기도 마찬가지로 만료된 청원 정도의 메시지면 좋을 것 같아요

2022-02-19 13:01 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/presentation/PetitionController.java
> +    public ResponseEntity<Page<PetitionPreviewResponse>> retrieveReleasedAndExpiredPetitions(@RequestParam(defaultValue = "0") Long categoryId,
PetitionPreviewResponse에 expired 칼럼이 필요할 것 같아요!

2022-02-19 13:02 UTC, koseyeon commented on src/main/java/com/gistpetition/api/petition/application/PetitionService.java
> +    public Page<PetitionPreviewResponse> retrieveReleasedAndNotExpiredPetition(Pageable pageable) {
네 동의합니다! ㅎㅎ

2022-02-19 14:43 UTC, wannte requested changes
몇가지 코멘트 더 남겼습니다 확인부탁드려요!

2022-02-19 14:43 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/application/PetitionService.java
> +        return PetitionPreviewResponse.pageOf(petitionRepository.findAllByCreatedAtBeforeAndReleasedTrue(LocalDateTime.now().minusDays(31), pageable));
30 -> Petition의 상수값을 import 하는 방식으로 진행하면 좋을 것 같아요!

정책이 수정될 때마다, 모든 코드를 순회해야 할 것 같아요.

2022-02-19 14:43 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/application/PetitionService.java
> +        return PetitionPreviewResponse.pageOf(petitionRepository.findAllByCreatedAtAfterAndReleasedTrue(LocalDateTime.now().minusDays(30), pageable));
여기도 마찬가지!

2022-02-19 14:43 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/presentation/PetitionController.java
> +        return ResponseEntity.ok().body(petitionService.retrieveExpiredPetitionByCategoryId(categoryId, pageable));
release가 된 경우만을 조건으로 추가해줘야 할 것 같아요!

2022-02-19 14:43 UTC, wannte commented on src/test/java/com/gistpetition/api/petition/application/PetitionServiceTest.java
> +    }
만료된 청원을 조회하는 테스트는 아닌것 같아요!

구현하기 힘든 상황인거 같은데, 삭제해도 좋을 것 같아요!

2022-02-20 07:32 UTC, GuruneLee commented on src/test/java/com/gistpetition/api/petition/application/PetitionServiceTest.java
> +        petitions.getContent().forEach(petitionPreviewResponse -> assertFalse(petitionPreviewResponse.getExpired()));
두개를 생성했으니, retrieveOngoing() 메서드 결과에 2개의 petition 이 담겨있는지 확인해야할 듯 합니다.

```
assertThat(petitions.getContent()).hasSize(2);
```

2022-02-20 07:32 UTC, GuruneLee commented on src/main/java/com/gistpetition/api/petition/application/PetitionService.java
> +        return PetitionPreviewResponse.pageOf(petitionRepository.findAllByCreatedAtBeforeAndReleasedTrue(LocalDateTime.now().minusDays(31), pageable));
그런데, 만료된 청원 불러오는거랑, release 여부랑 어떤 연관이 있죠?
expired petition을 불러오는데 왜 ReleaseTrue 가 오는건지 모르겠슴다

2022-02-20 07:32 UTC, GuruneLee commented on src/main/java/com/gistpetition/api/petition/application/PetitionService.java
> +        return PetitionPreviewResponse.pageOf(petitionRepository.findAllByCreatedAtAfterAndReleasedTrue(LocalDateTime.now().minusDays(30), pageable));
여기도 왜 ReleasedTrue 인지 잘 모르겠습니다.

2022-02-20 07:32 UTC, GuruneLee commented on src/test/java/com/gistpetition/api/petition/application/PetitionServiceTest.java
> +        petitions.getContent().forEach(petitionPreviewResponse -> assertFalse(petitionPreviewResponse.getExpired()));
그리고, retrieve 할때 ReleasedTrue 조건이 있어서 청원이 0개 담겨오는 듯 합니다

2022-02-20 07:45 UTC, GuruneLee commented on src/main/java/com/gistpetition/api/petition/application/PetitionService.java
> +        return PetitionPreviewResponse.pageOf(petitionRepository.findAllByCreatedAtBeforeAndReleasedTrue(LocalDateTime.now().minusDays(31), pageable));
고세연답변)
청원 리스트엔 Released True 인 청원만 포함되기에, 이 메서드를 사용해야한다.

테스트를 잘못짠거다.

2022-02-20 10:31 UTC, wannte requested changes
Test 하기 쉽지 않은 부분들을, `@MockBean` `@SpyBean`을 사용함으로써 해결했군요! 많이 배워갑니다.

몇가지 궁금한 부분들 남겼습니다. 확인 부탁드려요!

2022-02-20 10:31 UTC, wannte commented on src/test/java/com/gistpetition/api/petition/application/PetitionServiceTest.java
> +        releasePetitionByIds(createdPetitionIds);
메소드는 하나의 역할을 해야하는데요,

지금의 경우에는 5명의 동의 작업을 진행하고 난후, release를 진행하고 있네요!

별도로 분리함으로써 가독 성을 높일 수 있다고 생각해요!

2022-02-20 10:31 UTC, wannte commented on src/test/java/com/gistpetition/api/petition/application/PetitionServiceTest.java
> +        }
해당 유저들을 사용하지 않는 테스트에 경우에도 5번의 insert 구문이 진행될 것으로 보이는데요,

이는 바로 테스트 성능의 저하로 연결될 것이라 생각되네요!

이 부분을 감수하더라도 이 방식으로 진행해서 코드의 중복을 줄이는 것이 좋은 판단일지,
아니면 성능을 위해 어느 정도의 중복을 허용해주는 것인지에 대한 타협점에 있는 거라 생각되네요!

메소드 분리를 잘하면 이쁘게 정리가 될거 같기도 하고요!

지금의 구조도 좋습니다만, 이러한 부분에 대한 고려도 진행됬을까해서 남겨봐요!

2022-02-20 10:31 UTC, wannte commented on src/test/java/com/gistpetition/api/petition/application/PetitionServiceTest.java
> +    void retrieveExpiredPetition() {
이후에 로직이 변경되었을 때, (agree, release는 만료된 청원에 경우에 대해서는 exception을 뱉어야 할 것 같은데요)

이 부분이 수정되었을 때, agree를 하는 부분에서부터 에러가 발생할 것으로 보이는데, 어떤 방식으로 해결할 수 있을까요?

지금의 구현을 그대로 두고 다음 사람의 채무로 남겨도 좋습니다만, 다음 작업으로 인해 이 테스트가 삭제되지 않기 위해서는 어느 정도 해결책을 전달해주어야 할 것 같아요!

2022-02-20 10:31 UTC, wannte commented on src/test/java/com/gistpetition/api/petition/application/PetitionServiceTest.java
> +    private DateTimeProvider dateTimeProvider;
`@SpyBean`는 어떠한 경우에 사용하는 지, 그리고 지금의 경우에서 사용한 이유는 무엇인지 궁금합니다! (SpyBean을 사용해본 적이 없어서 질문차 남깁니다) `@Autowired`를 사용했을 때와는 어떤 점이 다른지 궁금합니다!

2022-02-20 10:31 UTC, wannte commented on src/test/java/com/gistpetition/api/petition/application/PetitionServiceTest.java
> +        when(dateTimeProvider.getNow()).thenReturn(Optional.of(pastTime));
MockBean을 사용하지 않고, 지금의 경우에만 dateTimeProvider를 설정해주는 것은 어떨까요?

```java
        auditingHandler.setDateTimeProvider(
                () -> Optional.of(LocalDateTime.of(2020, 12, 1, 0, 0))
        );
```

2022-02-20 10:42 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/application/PetitionService.java
> +        return PetitionPreviewResponse.pageOf(petitionRepository.findAllByCreatedAtBeforeAndReleasedTrue(LocalDateTime.now().minusDays(31), pageable));
피드백을 먼저 반영해주고 resolve처리를 해줘야 할것 같습니다. 계속 쌓이기만 하면, 보기 불편할 것 같아요!

2022-02-21 07:52 UTC, GuruneLee commented on src/test/java/com/gistpetition/api/petition/application/PetitionServiceTest.java
> +    private DateTimeProvider dateTimeProvider;
1. Autowired 를 사용하지 않는 이유
: autiwired 가 안됩니다. AuditingHandler 는 bean 으로 등록되어있지 않아서 의존성 주입을 할 수 없는듯 합니다.

2. DateTimeProvider 만 mocking 해도 되지 않나요?
: DateTimeProvider 는 spring ApplicationContext 에서 관리하지 않습니다. 따라서 DateTimeProvider 를 모킹해봤자, AuditingHandler 에 적용되지 않습니다. setter 를 사용해 직접 넣어줘야 합니다.

3. SpyBean 을 사용한 이유
: AuditingHandler 는 Autowired 가 안됩니다... (그런데 어떻게 Entity Listener가 이걸 사용하는걸까요..?) 그래서 spy bean 으로 생성해서 사용합니다. 이렇게 생성된 spy bean 을 가져다 사용하는것 같네요. 정확히 어떤 메커니즘인지는 모르겠습니다.

2022-02-21 08:04 UTC, GuruneLee commented on src/test/java/com/gistpetition/api/petition/application/PetitionServiceTest.java
> +        when(dateTimeProvider.getNow()).thenReturn(Optional.of(pastTime));
되네요!
그런데, 제가 저 람다식을 이해를 못하겠네요.
저렇게 하면 DateTimeProvider 가 생성이 되나요????

일단 반영해서 커밋올릴게요

2022-02-21 08:05 UTC, koseyeon commented on src/main/java/com/gistpetition/api/petition/application/PetitionService.java
> +        return PetitionPreviewResponse.pageOf(petitionRepository.findAllByCreatedAtBeforeAndReleasedTrue(LocalDateTime.now().minusDays(31), pageable));
네 반영하겠습니다!

2022-02-21 08:08 UTC, GuruneLee commented on src/test/java/com/gistpetition/api/petition/application/PetitionServiceTest.java
> +        when(dateTimeProvider.getNow()).thenReturn(Optional.of(pastTime));
메서드가 하나밖에 없는 인터페이스라 가능한건가...?

2022-02-21 08:08 UTC, GuruneLee commented on src/test/java/com/gistpetition/api/petition/application/PetitionServiceTest.java
> +    private DateTimeProvider dateTimeProvider;
AuditingHandler 를 어떻게 가져다 쓰는건지 모르겠어!!!!!!

2022-02-21 08:22 UTC, koseyeon reviewed
창하가 진행중인 부분을 제외하고 앞선 리뷰 사항 반영했습니다!

2022-02-21 08:22 UTC, koseyeon commented on src/main/java/com/gistpetition/api/petition/presentation/PetitionController.java
> +        return ResponseEntity.ok().body(petitionService.retrieveExpiredPetitionByCategoryId(categoryId, pageable));
petitionService.retrieveExpiredPetition이 release되고 expired된 것만 가져오는 메소드인데 메소드 이름이 명확하지 않았네요 수정하겠습니다!

2022-02-21 13:51 UTC, wannte commented on src/test/java/com/gistpetition/api/petition/application/PetitionServiceTest.java
> +        when(dateTimeProvider.getNow()).thenReturn(Optional.of(pastTime));
혼자서 잘하는 군요 👍

2022-02-21 13:54 UTC, wannte approved these changes
쉽지 않았던 pr인데, 잘 마무리 해주셨네요!

수고하셨습니다!

2022-02-21 13:56 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/presentation/PetitionController.java
> +        return ResponseEntity.ok().body(petitionService.retrieveExpiredPetitionByCategoryId(categoryId, pageable));
오홍,, 내가 잘못봤었구나, 나는 repository에 realease=true 조건을 안 넣어준걸로 봤거든! ㅋㅋ 전에 메소드명도 좋고, 지금의 메소드 명도 좋습니다!

2022-02-21 13:57 UTC, wannte commented on src/test/java/com/gistpetition/api/petition/application/PetitionServiceTest.java
> +    private DateTimeProvider dateTimeProvider;
새로운 경험 1스택 추가..
https://docs.spring.io/spring-framework/docs/3.0.0.M4/reference/html/ch07s08.html
함께 위 글 읽어 보는 시간을 가지죠

2022-02-21 15:27 UTC, merged