feat: petition 엔터티의 agreements 를 일급객체로 분리하였다.
GIST-Petition-Site-Project/GIST-petition-server pull request #280
Opened 2022-03-06 11:54 UTC by GuruneLee

기존 List<Agreement> 로 선언되었던 agreements 를 Agreements 라는 일급 객체로 분리하고, agreements 에 관련된 로직을 이에 포함시켰습니다.

---
이렇게 petition 엔터티의 역할이 일부 Agreements로 이동함에 따라, petition test 중, 'agreements 내부 데이터 검증' 과 'agreements 리스트 길이 검증' 부분을 삭제하였습니다. 이는 Agreements 테스트에서 이루어졌고 petition 은 agreeCount의 변화만 검증하면 된다는 판단이었습니다.

---
petition 엔터티 객체 정의가 바뀌었지만, ddl 의 변화는 없는것으로 확인되었습니다. 따라서, flyway migration 추가는 필요 없습니다.

2022-03-06 12:11 UTC, ChoiEungi approved these changes
분리하니 Petition로직이 훨씬 깔끔해졌네요! 고생많으셨습니다 :)

2022-03-06 12:11 UTC, ChoiEungi commented on src/main/java/com/gistpetition/api/petition/domain/Agreements.java
> +    public Agreements() {
protected 혹은 `@NoArgsConstructor(PROTECTED)`를 사용하는건 어떨까요?

2022-03-06 12:11 UTC, ChoiEungi commented on src/test/java/com/gistpetition/api/agreement/AgreementsTest.java
> +        Long notWriterId = userIdList.get(userIdList.size() - 1) + 1;
`Long.MAX_VALUE`를 사용하는건 어떨까요?

2022-03-06 12:12 UTC, GuruneLee commented on src/test/java/com/gistpetition/api/agreement/AgreementsTest.java
> +        Long notWriterId = userIdList.get(userIdList.size() - 1) + 1;
똑똑한 생각입니다

2022-03-06 12:12 UTC, GuruneLee commented on src/main/java/com/gistpetition/api/petition/domain/Agreements.java
> +    public Agreements() {
액설런트 익스프레스 입니다

2022-03-06 12:13 UTC, GuruneLee commented
리뷰는 내일 반영할게요

2022-03-06 13:52 UTC, wannte requested changes
gosang gosang!

2022-03-06 13:52 UTC, wannte commented on src/test/java/com/gistpetition/api/petition/application/PetitionServiceTest.java
> +        userRepository.saveAll(users);
조금이라도 빠르게ㅔ....

2022-03-06 13:52 UTC, wannte commented on src/test/java/com/gistpetition/api/agreement/AgreementsTest.java
> +    }
writer가 어떤 것을 의미하는지 궁금합니다!

또한 이 테스트의 목적이 어떤 것인지 궁금합니다!

4명의 유저리스트에 동의를 추가했는데, 첫번째 유저 만을 검증하는 테스트는 어떤 의도로 작성되었는지 궁금합니다!

2022-03-06 13:52 UTC, wannte commented on src/test/java/com/gistpetition/api/agreement/AgreementsTest.java
> +        Long notWriterId = userIdList.get(userIdList.size() - 1) + 1;
여기서도 writer가 어떤 의미를 지니는 지 궁금합니다!

또 10명의 동의를 하고 나서, 그 마지막 사람의 id에 1을 더한 사람을 조회에 사용했는데요,

아무런 동의가 없는 상황에서 조회를 했을 때, isAgreedBy가 false를 나타내는 것과는 어떤 의도의 차이가 있는지도 궁금하네요

개인적인 취향으로는 테스트는 간단히 쳐낼 수 있는 테스트는 간단하게 쳐내는 것도 좋은 방법이라 생각합니다.! 테스트의 의도가 한눈에 들어올 수 있으면 더 좋고요!

2022-03-06 13:52 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/domain/Agreements.java
> +    public List<Agreement> getAgreementList() {
```
2. 그릇된 정보를 피하라.
실제 변수의 자료형이 List가 아닌데 네이밍에 list가 포함하는 걸 추천하지 않는다.

물론, 컨테이너가 List인 경우라도 컨테이너 유형을 이름에 넣지 않는 편이 바람직하다.
```

클린 코드 책의 네이밍 부분의 발췌 부분입니다. 함수 시그니쳐로 그 의미가 충분히 들어나 있기 때문에 List라는 말을 사용하지 않는 것은 어떨까요?

변수명에서도 마찬가지인데, 지금의 구조에서는 List로 사용되고 있지만, 우리 비지니스 적인 로직에 변화로 Set을 사용하는 것으로 변경하게 된다면 많은 부분 수정을 진행해야 할 수도 있을 것 같아요.(변경에 취약한 코드가 될 것 이라는 생각입니다!)

물론 클래스명이 Agreements인데 안에 변수명 또한 agreeements를 사용하는 부분이 조금은 어색하게 보이긴하네요. 개인 적인 취향으로는 agreementList로 그 구현체의 정보를 들어내서 고정하는 것보다는, agreements를 사용하는 것이 더 좋을 것 같다는 생각입니다. items라는 명명을 쓸수도 있을 거라 생각이 드는데, 오해를 살수 있는 명명법 같다는 생각도 드네요!

2022-03-07 08:53 UTC, GuruneLee commented
완태님이 지적해주신 테스트 부분의 간략화를 진행했습니다.

다시보니, 의도가 명확히 드러나지 않는것 같았습니다.

많이 배웁니다.

2022-03-07 09:59 UTC, wannte approved these changes
피드백 반영 확인했습니다! 👍 
수고하셨습니다.

2022-03-07 12:19 UTC, merged