refactor: 청원의 제목,내용에 길이 제한을 두기 위해 Embeddable class를 사용하도록 함.
GIST-Petition-Site-Project/GIST-petition-server pull request #288
Opened 2022-03-09 14:28 UTC by koseyeon

close #281 

청원의 제목, 내용에 길이 제한을 주기 위해 Title, Description Embeddable Class를 만들고 Petition이 해당 타입의 값들을 가지도록 했습니다.

다른 도메인에도 적용해보려 했는데 오늘은 시간이 안나서 내일 시간이 되는대로 해보겠습니다!

2022-03-10 07:52 UTC, wannte requested changes
리뷰 남겼습니다! 확인 부탁드려요!

2022-03-10 07:52 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/domain/Description.java
> +    public static final int DESCRIPTION_MAX_LENGTH = 10000;
상수는 클래스의 상단에 위치하면 좋을 거 같아요!

2022-03-10 07:52 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/domain/Description.java
> +        if (Objects.isNull(description) || description.isBlank() || description.length()>DESCRIPTION_MAX_LENGTH) {
```suggestion
        if (Objects.isNull(description) || description.isBlank() || description.length() > DESCRIPTION_MAX_LENGTH) {
```

2022-03-10 07:52 UTC, wannte commented on src/main/java/com/gistpetition/api/exception/petition/InvalidDescriptionException.java
> +    private static final String MESSAGE = "내용 길이가 올바르지 않습니다.";
description 내용 길이에 관한 에런데,

InvalidDescriptionLengthException은 어떨까요?

InvalidDescriptionException는 조금 추상적인 정의라 생각합니다! 이후에 다른 에러가 description 내부에서 사용된 다면, 헷갈릴 수도 있을 것 같아요.

예를 단어가 포함되었을 때, 에러를 뿜는다고 하면 InvalidDescriptionException 이걸 쓸 거 같은 느낌이에요!

2022-03-10 07:52 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/domain/Description.java
> +public class Description {
Description에 청원의 내용이라는 의미가 더 들어갔으면 좋겠다는 생각이에요!

Agreement나 Answer에 내용에 대한 부분도 구현을 진행할 예정인데, 명확하게 명시해줘도 좋을 것 같다는 생각입니다!

2022-03-10 07:52 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/domain/Petition.java
> +        this.category = Category.of(categoryId);
매번 새로운 객체를 할당하는 것 보다, 각 객체에  메시지를 보내는 방법은 어떨까요?

this.title.update()

2022-03-10 07:52 UTC, wannte commented on src/test/java/com/gistpetition/api/petition/application/PetitionServiceTest.java
> +    void createPetitionWithInvalidTitleAndDescription() {
Service레이어가 아닌 도메인 레이어에서 진행하는 것은 어떨까요?

2022-03-11 06:17 UTC, koseyeon commented on src/main/java/com/gistpetition/api/petition/domain/Description.java
> +    public static final int DESCRIPTION_MAX_LENGTH = 10000;
아 네 알겠습니다!

2022-03-11 06:18 UTC, koseyeon commented on src/main/java/com/gistpetition/api/petition/domain/Description.java
> +        if (Objects.isNull(description) || description.isBlank() || description.length()>DESCRIPTION_MAX_LENGTH) {
띄어쓰기 하겠습니다!

2022-03-11 06:19 UTC, koseyeon commented on src/main/java/com/gistpetition/api/exception/petition/InvalidDescriptionException.java
> +    private static final String MESSAGE = "내용 길이가 올바르지 않습니다.";
저도 이 부분 고민했었는데 Length를 붙이는게 좀더 명확한것 같네요!!

2022-03-11 06:21 UTC, koseyeon commented on src/main/java/com/gistpetition/api/petition/domain/Description.java
> +public class Description {
이 부분도 고민하다가 Petition 도메인 패키지 안에 있어서 Petition을 또 붙이면 의미가 중복되는것 같아 Description으로만 했는데 붙이는게 더 나을까요??

2022-03-11 06:22 UTC, koseyeon commented on src/main/java/com/gistpetition/api/petition/domain/Petition.java
> +        this.category = Category.of(categoryId);
오 좋습니다!!

2022-03-11 06:32 UTC, koseyeon commented on src/test/java/com/gistpetition/api/petition/application/PetitionServiceTest.java
> +    void createPetitionWithInvalidTitleAndDescription() {
아 제가 서비스 레이어에 테스트를 만든 이유는,
도메인 레이어 테스트는 도메인 객체가 생성된 이후에,
해당 객체가 가지고 있는 역할들을 테스트 하는것이 아닐까하고 생각해서였습니다! 

제가 생각했을 때 createPetitionWithInvalidTitleAndDescription 테스트는 
Petition 도메인 객체 생성이 목적인 테스트 이고, 해당 도메인 객체가 어떤 역할을 잘 수행하는지를 테스트 하는 것은 아니므로 서비스레이어에서 테스트 하면 어떨까 했습니다 ㅎ,,,

2022-03-11 08:11 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/domain/Description.java
> +public class Description {
우선은 그냥 두고 다음 작업을 진행할 때, 수정을 진행해도 좋을 것 같아요.

2022-03-11 08:15 UTC, wannte commented on src/test/java/com/gistpetition/api/petition/application/PetitionServiceTest.java
> +    void createPetitionWithInvalidTitleAndDescription() {
'객체 생성'을 서비스 레이어에서 테스트했을 떄 어떤 장점이 있을까요?

2022-03-11 15:36 UTC, koseyeon commented on src/test/java/com/gistpetition/api/petition/application/PetitionServiceTest.java
> +    void createPetitionWithInvalidTitleAndDescription() {
객체 생성을 서비스 레이어에서 테스트 할때
장점: 객체에 따라서 생성될 때 DataIntegrity을 위배하고 있지 않은 지 등 서비스레이어 단에 걸려있는 조건들까지 검증할수 있다.
단점: 테스트가 도메인레이어에서 진행할때보다 무거워진다
이렇게 볼수 있을것 같습니다

2022-03-11 15:41 UTC, wannte commented on src/test/java/com/gistpetition/api/petition/application/PetitionServiceTest.java
> +    void createPetitionWithInvalidTitleAndDescription() {
`DataIntegrity을 위배하고 있지 않은 지 등 객체를 생성하기 위해 거쳐야하는 서비스레이어 단에 걸려있는 조건들` 이게 구체적으로 어떤 게 있을까요?

2022-03-12 08:23 UTC, koseyeon commented on src/test/java/com/gistpetition/api/petition/application/PetitionServiceTest.java
> +    void createPetitionWithInvalidTitleAndDescription() {
만나서 자세한 설명 들었습니다 감사합니다! 😊

2022-03-12 08:24 UTC, wannte approved these changes
은기 축하해

2022-03-12 08:24 UTC, merged