feat: 청원 반려 기능 구현
GIST-Petition-Site-Project/GIST-petition-server pull request #330
Opened 2022-03-24 08:34 UTC by GuruneLee

@koseyeon 
@ChoiEungi 

당.장.리.뷰.해.

2022-03-24 09:29 UTC, wannte requested changes

2022-03-24 09:29 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/domain/Petition.java
> +    public void reject(String description, Instant at) {
사소한 것이지만, release관련 메소드 뒤에 위치시키면 더 좋을 것 같아요!

2022-03-24 09:29 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/presentation/PetitionQueryController.java
> +    @GetMapping("/petitions/rejected")
창하씨 우리 커맨드 컨트롤러는 안만들었네요 ㅎㅎ

2022-03-24 09:29 UTC, wannte commented on src/main/java/com/gistpetition/api/DataLoader.java
> +    public static final int WAITING_FOR_CHECK_ANSWER_COUNT = 3;
숫자 원복이 필요합니다

2022-03-25 02:10 UTC, ChoiEungi reviewed
고생하셨습니다!

2022-03-25 02:10 UTC, ChoiEungi commented on src/main/java/com/gistpetition/api/petition/domain/Petition.java
> +    @OneToOne(fetch = FetchType.EAGER, cascade = CascadeType.PERSIST, orphanRemoval = true)
Eager로 Fetch하는 이유가 무엇인가요?

2022-03-25 05:30 UTC, GuruneLee commented on src/main/java/com/gistpetition/api/petition/domain/Petition.java
> +    @OneToOne(fetch = FetchType.EAGER, cascade = CascadeType.PERSIST, orphanRemoval = true)
비즈니스적으로 petition 을 요구하는 모든 요청에 필요하다고 판단하였습니다.

또한 one to one 이기 때문에 큰 오버헤드도 없을 것 같았구요

2022-03-25 06:42 UTC, wannte commented on src/main/java/com/gistpetition/api/petition/domain/Petition.java
> +    @OneToOne(fetch = FetchType.EAGER, cascade = CascadeType.PERSIST, orphanRemoval = true)
지금 와서 생각해보면, Lazy하는 게 더 좋을 거 같다는 생각도 드네요 ㅎㅎ

agree하는 시점에 refected 체크를 진행하지만, 아마 여기서 별도의 쿼리가 나가지 않을 거에요 (null 비교는 petition테이블의 rejection_id로 가능하기 때문에!)

실제 rejection Lazy 로딩으로 설정했을 때, 별도의 쿼리가나가는 경우는 reject를 수정하는 경우 또는 개별 조회할 때 밖에 없겠네요!

마찬가지로 answer 부분도 Lazy 로딩의 사용도 좋아보입니다. ㅎㅎㅎ

2022-03-25 06:43 UTC, wannte approved these changes
good!

2022-03-25 07:13 UTC, merged