feature: agreement 동의 기능 요구 사항 수정
GIST-Petition-Site-Project/GIST-petition-server pull request #62
Opened 2021-12-04 08:36 UTC by ChoiEungi

2021-12-04 09:14 UTC, wannte requested changes
테스트까지 깔끔하게 작성해주셨네요! :+1:

몇 가지 코멘트 남겼으니 확인부탁드려요!
코멘트는 제안일 뿐, 꼭 반영해야할 필요는 없습니다.
크게 수정사항이 필요할 경우에는, 별도 시간을 잡고 이야기하면 좋겠으나, 이번에는 너무도 잘 해주셨네요!

리뷰확인하시구 다시 요청하면, Approve하겠습니다~

> 한가지 추가로 Close #{issue number} 를 본문에 넣으면 자동으로 이슈 링크됩니다~

2021-12-04 09:14 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/post/Post.java
> +    private final List<Agreement> agreements = new ArrayList<>();
가장 위에 위치 시킨 이유가 있을까요?

2021-12-04 09:14 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/post/Post.java
> +                throw new CustomException(ErrorCase.INVALID_AGREEMENT);
:+1:

2021-12-04 09:14 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/post/Post.java
> +    }
getStateOfAgreement 만을 봤을 때, Agreement의 상태값을 리턴할 것 같다는 느낌이에요!

isAgreedBy(user)를 제안해봅니다!

2021-12-04 09:14 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/post/PostService.java
> +        Post post = postRepository.findById(postId).orElseThrow(() -> new CustomException(ErrorCase.NO_SUCH_POST_ERROR));
해당 메소드는 분리하는 것도 좋을 것 같아요!

2021-12-04 09:14 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/post/PostService.java
> +    @Transactional(readOnly = true)
JPA에서 `@Transactional` 어노테이션의 여부에 따라 동작이 달라지는데, 이 부분에 대해서 지금 완벽하게는 모르더라도, 이런 경험이 있었다! 정도만이라도 가지고 갔으면 좋겠어요~ :+1:

2021-12-04 09:14 UTC, wannte commented on src/test/java/com/example/gistcompetitioncnserver/post/PostServiceTest.java
> +                new PostRequestDto("title", "description", "category", user.getId()), user.getId());
동일하게 사용되는 부분인데,

`@BeforeEach`를 사용하여 분리해 보는 것은 어떨까요?

2021-12-04 11:44 UTC, ChoiEungi commented on src/main/java/com/example/gistcompetitioncnserver/post/Post.java
> +    private final List<Agreement> agreements = new ArrayList<>();
Intellij에서 reformat하다가 이러게 된 것 같습니다!

2021-12-04 13:46 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/post/Post.java
> +    private final List<Agreement> agreements = new ArrayList<>();
오호 혹시 이거 위치를 아래로 옮기는 건 어떨까요!?

내일 Intellij 설정 통일에 관련해서 이야기해도 좋을 것 같네요!

reformat할 때마다 파일이 변경되면 문제가될 것 같네요!

2021-12-04 13:50 UTC, wannte approved these changes
리뷰 반영 확인했습니다!
세연이와 의논해보고 머지 진행해도 좋을 것 같아요!

2021-12-04 13:50 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/post/PostService.java
> +        User user = userRepository.findById(userId).orElseThrow(() -> new CustomException(ErrorCase.NO_SUCH_USER_ERROR));
이 부분도 post와 마찬가지로 메소드 분리해도 좋겠네요!

2021-12-05 11:07 UTC, koseyeon approved these changes

2021-12-05 11:07 UTC, koseyeon commented on src/main/java/com/example/gistcompetitioncnserver/post/Post.java
> +    }
아 그렇네요 그게 더 좋은 것 같습니다!

2021-12-05 11:07 UTC, koseyeon commented on src/test/java/com/example/gistcompetitioncnserver/post/PostServiceTest.java
> +                new PostRequestDto("title", "description", "category", user.getId()), user.getId());
넵 
@BeforeEach
void setUp() {
User user = userRepository.save(new User("userName", "email", "password", UserRole.USER));
Long postId = postService.createPost(newPostRequestDto("title","description","category",user.getId()),user.getId());
}
이런 식으로 해보겠습니다!

2021-12-05 13:10 UTC, wannte commented on src/test/java/com/example/gistcompetitioncnserver/post/PostServiceTest.java
> +                new PostRequestDto("title", "description", "category", user.getId()), user.getId());
:+1:

2021-12-05 13:37 UTC, koseyeon approved these changes

2021-12-05 13:39 UTC, merged