Refactor/answer
GIST-Petition-Site-Project/GIST-petition-server pull request #72
Opened 2021-12-23 09:24 UTC by koseyeon

answer entity, controller, service에 대한 리팩토링을 진행했습니다.
진행 주요 내용
1. answer가 postId를 가지고 있는 구조로 만들었습니다.(comment와 같은 구조입니다)
2. answerRequestDto를 만들었습니다.
3. 답변을 카테고리 별로 조회하는 기능은 삭제하였습니다. (현재 answer가 post에 의존하기 때문에 post에만 카테고리 분류기능이 있으면 될 것으로 생각했습니다.)
남은 작업 AnswerService에서 createAnswer할떄 answer에 대해 검증하는 부분이 필요합니다.

2021-12-24 08:51 UTC, wannte commented
pr 제목이 불편합니다.

2021-12-24 09:10 UTC, wannte requested changes
사용되지 않는 import, filed가 존재하네요! 이 부분에 대해서는 항상 깔끔하게 정리했으면 좋겠습니다!

도메인이 DTO에 의존하는 부분은 함께 이야기 해봤으면 좋겠습니다!

2021-12-24 09:10 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/answer/AnswerController.java
> +@RequestMapping("/v1") // not used in rest api like v1 url
기존의 주석도 함께 지워도 좋을 것 같아요!

2021-12-24 09:10 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/answer/AnswerController.java
> +    private boolean isRequestBodyValid(AnswerRequestDto answerRequestDto) {
private 메소드의 위치는 사용하는 public 메소드 밑으로 넣으면 좋을 것 같아요! (우리 팀의 컨벤션으로 가져가는 건 어떨까요?)

- 하나의 public 메소드에서만 사용되는 private 메소드: 해당 public 바로 밑에
- 동시에 여러 군데에서 사용되는 경우에는 코드의 하단부에 위치시킨다.

2021-12-24 09:10 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/answer/AnswerController.java
> +        return answerRequestDto.getContent() != null ;
이 부분은 나중에 추후에 `spring validation`을 도입해도 좋을 것 같네요!

2021-12-24 09:10 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/answer/AnswerController.java
> +    public Optional<Answer> retrieveAnswer(@PathVariable Long postId,@PathVariable Long answerId){
Controller의 리턴값이 Optional이면 위험할 것 같아요!
null인 경우에는 별도의 Exception을 만드는 것은 어떨까요?

2021-12-24 09:10 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/answer/AnswerService.java
> +        // TODO answer 검증하기
Manager의 권한을 가진 경우 Answer의 생성, 삭제의 검증을 해도 좋을 것 같아요!

아니면, 이 부분에 대해서는 별도로 이슈를 잡고 진행해도 좋을 것 같아요!

2021-12-24 09:10 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/answer/Answer.java
> +    public Answer(AnswerRequestDto answerRequestDto, Long postId, Long userId) {
도메인이 DTO에 의존하게 되는데요, 이 부분은 조심스럽네요!

2021-12-24 09:10 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/answer/Answer.java
> +    private String content;
title을 삭제한 이유가 있을까요??

2021-12-24 09:10 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/answer/AnswerController.java
> +//        answerService.deleteAnswer(answerId);
주석은 무조건 없애기!
기능의 구현이 필요하다면, 해당 작업 이슈에 남기도록 합시다!

2021-12-26 07:12 UTC, koseyeon commented on src/main/java/com/example/gistcompetitioncnserver/answer/AnswerController.java
> +@RequestMapping("/v1") // not used in rest api like v1 url
넵!

2021-12-27 13:29 UTC, wannte requested changes
테스트 코드 어마어마하네요 :+1: :+1: 

코드를 읽기도 너무 편해서, 리뷰하는데도 좋았습니다!

수정이라기 보다는, 함께 이야기 하고 싶은 부분 위주로 피드백 남겼습니다. 확인 부탁드려요!

가능하면, 내일 오전에 같이 2개의 PR 머지하고 다음 작업 잡고 진행했으면 좋겠습니다!

2021-12-27 13:29 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/answer/AnswerController.java
> +@RequestMapping("/v1") // not used in rest api like v1 url
`// not used in rest api like v1 url` 지워주세요!

2021-12-27 13:29 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/answer/AnswerService.java
> +        }
create/update/delete 에 관하여 공통으로 남기는 피드백입니다.

1. getter를 사용해 정보를 가지고 와서 비교하기 보다는 객체에 질의를 던지는 방식은 어떨까요?
- `user.canWriteAnswer(Post post)`, `user.canUpdateAnswer(Answer answer)`, `user.canDeleteAnswer(Answer answer)` 
- `post.canAnsweredBy(User user)`, `answer.canUpdatedBy(User user)`, `answer.canDeletedBy(User user)`

정도의 메소드 명이 되겠네요!

> 만약 이 부분의 도입을 하게 된다면, 저랑 은기의 생각은 후자입니다. 저희 구조상 post가 user에 의존(post가 user를 알고 있음:userId를 가지고 있음), answer가 post와 user에 의존(comment가 userId, postId를 가지고 있음) 이렇게 의존성의 방향이 흐릅니다. 만약 전자의 방법을 선택한다면 user가 post와 comment라는 객체를 알게되는 구조가 되기 때문에 양방향 의존성이 흐르기 때문에, 후자의 방법이 더 적합하다 판단했습니다.) - 이 부분에 대해서 만나서 줌으로 설명해도 좋을 것 같습니다!

- 객체 안에 객체 안에 객체를 계속 타고타고 들어가면서 검증을 진행한다면, 오히려 검증 과정을 확인하기가 불편할 것 같고, 그런 경우에는 지금의 방식으로 구현을 진행하는 것도 좋은 방법이 될 것이라 생각합니다.
- 반면에, 객체에 메시지를 보내는 방식으로 진행하게 되면 캡슐화를 진행하고 책임을 분리할 수 있을 것이라 생각해요. 이렇게 했을 때, 어떤 장점을 가지게 될지도 이야기 해봤으면 좋겠어요!


2. ADMIN의 권한에 관한 질문입니다!
권한 회의를 진행할 때, MANAGER의 모든 권한을 ADMIN이 가지게 결정되었는데요! 지금의 구현에서는 이 요구사항을 지키기에는 부족한 것 같다고 생각합니다!

다른 부분을 염두하고 지금의 방식으로 구현한 것 같은데, 그 생각을 듣고 싶습니다!

2021-12-27 13:29 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/answer/AnswerService.java
> +    }
```suggestion
    private Answer findAnswerByPostId(Long postId) {
        return answerRepository.findByPostId(postId)
                       .orElseThrow(() -> new CustomException("해당 post에는 답변이 존재하지 않습니다."));
    }
```

요 정도로 위와 형태를 맞추는 것도 좋을 것 같다는 생각입니다! (요건 개인 취향) 결정은 여러분의 생각대로!

2021-12-27 13:29 UTC, wannte commented on src/test/java/com/example/gistcompetitioncnserver/answer/AnswerServiceTest.java
> +        Answer answer = answerRepository.findById(savedAnswer).orElseThrow(()-> new CustomException("존재하지 않는 answer입니다.;"));
요 부분도 자주 사용되서 메소드 분리를 진행해도 좋을 것 같아요!

2021-12-27 13:29 UTC, wannte commented on src/test/java/com/example/gistcompetitioncnserver/answer/AnswerServiceTest.java
> +    void deleteAnswerByOther() {
```suggestion
    void deleteAnswerByOtherManager() {
```
헷갈릴것 같아요!

2021-12-27 13:29 UTC, wannte commented on src/test/java/com/example/gistcompetitioncnserver/answer/AnswerServiceTest.java
> +    }
앞 부분 `객체에게 물어봐라`의 연장선입니다.

테스트 코드를 보다보니, 떠오른 생각인데요!
만약 객체에 답글의 CUD  검증 로직을 추가하게 된다면, 지금의 Service테스트에서는 허용된 사용자, 허용되지 않는 사용자에 대한 테스트를 진행하고, 도메인의 테스트에서 지금의 다양한 상황들에 대해 테스트를 진행할 수도 있을 것 같네요!

2021-12-27 13:29 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/answer/AnswerController.java
>      }
이 메소드의 존재여부에 대해 의문점이 드네요!

하나만 존재할 수 있는 answer의 갯수가 어떤 의미를 가질까? 라는 의문이 듭니다!
이 부분은 post의 answered 칼럼으로 보여주는게 더 좋지 않을까요?

추가적으로 post가 답변됬는지에 대한 정보를 가지고 있어야 하나?에 대한 개인적인 궁금증도 있습니다! 요 부분은 이번에 진행한 부분이 아니지만, 함께 이야기해봤으면 좋을 것 같아서 남겨봐요! (동일한 데이터를 두번 별도로 저장하는 느낌?)

2021-12-28 12:06 UTC, GuruneLee commented on src/test/java/com/example/gistcompetitioncnserver/answer/AnswerServiceTest.java
> +        Answer answer = answerRepository.findById(savedAnswer).orElseThrow(()-> new CustomException("존재하지 않는 answer입니다.;"));
테스트의 가독성을 위해서, 그대로 놔두는 것이 좋다고 생각했습니다.

2021-12-28 12:10 UTC, GuruneLee commented on src/main/java/com/example/gistcompetitioncnserver/answer/AnswerService.java
> +        }
admin의 권한을 추가하였습니다.
또한, can--- 메서드를 일단 바꾸지 않기로 결정하고 진행하였습니다.
왜냐하면, 아직 도메인 주도 설계에 대한 지식이 부족하여 특성을 제대로 이해하지 못한 상태에서 수정을 하는것이 위험하다고 판단했기 때문입니다.
모두가 ddd에 더 나은 이해도를 가지고 있을때 다시 판단하길 원합니다.

2021-12-28 12:13 UTC, GuruneLee commented on src/test/java/com/example/gistcompetitioncnserver/answer/AnswerServiceTest.java
> +    }
위에 답변 참고해주세요

2021-12-28 13:02 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/answer/AnswerService.java
> +        }
네, 저도 지금 상황에서 두가지 중 어떠한 방법이 더 좋다고 설득시킬만한 근거가 부족하고, 지금의 방식이 가지는 장점도 있다 생각합니다!

다만, `도메인 주도 설계`의 개념과는 조금 떨어진 개념이라 생각해요! 지금의 경우에는 `객체의 캡슐화` `책임의 분리` `객체에게 질문을 던져라` 요정도 키워드라 생각하고 `객체 지향`의 키워드와 더 밀접하다고 생각이 드네요!

저도 아직 도메인 주도 설계에 대한 개념이 명확히 잡혀있지 않아서 해당 개념에 대해 설명을 달기에는 부족하지만 같이 공부해나가죠!

2021-12-28 13:03 UTC, wannte commented on src/test/java/com/example/gistcompetitioncnserver/answer/AnswerServiceTest.java
> +        Answer answer = answerRepository.findById(savedAnswer).orElseThrow(()-> new CustomException("존재하지 않는 answer입니다.;"));
굳이 분리하지 않는 것이 때로는 읽기 더 편한 코드가 되죠! :+1:

2021-12-28 13:10 UTC, wannte approved these changes
피드백 반영하느라 고생많았습니다!

conflict만 해결하고 머지 진행해도 좋을 것 같습니다!

2021-12-28 13:10 UTC, wannte commented on src/test/java/com/example/gistcompetitioncnserver/answer/AnswerServiceTest.java
> +        assertTrue(!answerRepository.existsById(answer.getId()));
기존의 구현이 가독성이 더 좋지 않을까? 라는 개인적인 생각 남겨두고 갑니다!

잘 기억은 안나는데, 클린 코드 책에서 가능하면 부정조건?을 피해라 요런 부분이 있던걸로 기억해요!

2021-12-29 01:49 UTC, merged