feat: dev profile에 Mysql 연결 설정 추가.
GIST-Petition-Site-Project/GIST-petition-server pull request #96
Opened 2022-01-06 02:37 UTC by koseyeon

현재 ec2에 mysql 을 도커로 띄워놓았고, 
application.yml 에 있는 dev profile에 
datasource(도커 Mysql), jpa 연결 설정 추가하였습니다.
데이터베이스에 로그인 하기 위한 USER_NAME, PASSWORD는 환경변수로 설정하였습니다. 
환경변수로 하는 것 보다 더 나은 방법이 있을지 논의하면 좋을것 같습니다.
close #68

2022-01-06 03:26 UTC, wannte requested changes
설정 파일을 수정하느라 고생했습니다!

혹시 이 부분이 실제로 동작하는지 확인을 해봤는지 알고 싶습니다.

또 MySql은 어떤 방식으로 띄울것인지에 대한 부분도 설명이 추가되었으면 좋겠습니다!

2022-01-06 03:26 UTC, wannte commented on src/main/resources/application.yml
> +    url: jdbc:mysql://dev-api.gist-petition.com:3306/dev_petitiondb?serverTimezone=Asia/Seoul
```suggestion
    url: jdbc:mysql://localhost:3306/dev_petitiondb?serverTimezone=Asia/Seoul
```
지금의 구현과 `localhost`를 이용한 구현에는 어떠한 차이점이 있을까요?

2022-01-06 03:26 UTC, wannte commented on src/main/resources/application.yml
> +    password: ${PASSWORD}
CI/CD가 구현된 상태에서, 환경변수를 어떤 방식으로 입력해 줄 수 있나요?

2022-01-06 03:26 UTC, wannte commented on src/main/resources/application.yml
> +      ddl-auto: update
`ddl-auto: update`를 사용한 이유가 궁금합니다.

2022-01-06 03:26 UTC, wannte commented on src/main/resources/application.yml
> +        format_sql: true
`show-sql: true`, `format_sql: true`는 어떤 역할을 하기에 추가해줬나요?

2022-01-06 03:36 UTC, koseyeon commented on src/main/resources/application.yml
> +    password: ${PASSWORD}
배포서버에 실제 환경변수값이 들어간 yaml 파일을 만들어 두고 커맨드라인에서 java -jar server.jar --spring.config.location=./{실제환경변수값이들어간버젼}.yaml 으로 실행하도록 하면 되지 않을까 생각합니다
참고한 블로그입니다 -> https://velog.io/@morningstar/env

2022-01-06 03:40 UTC, koseyeon commented on src/main/resources/application.yml
> +    url: jdbc:mysql://dev-api.gist-petition.com:3306/dev_petitiondb?serverTimezone=Asia/Seoul
아 제 로컬에서 테스트 해볼려고 저렇게 했었습니다 
배포서버와 mysql이 모두 같은 곳에 있으니 이제는 localhost로 바꿔도 될 것 같습니다.

2022-01-06 03:43 UTC, koseyeon commented on src/main/resources/application.yml
> +      ddl-auto: update
테이블을 제가 직접 만드는 것보다 
jpa를 통해서 자동생성해줄려고 ddl-auto를 썼고,
한번 만든 다음에는 매번 새로 생성되게 하는 것(ddl-auto:create)보다 
기존에 있던 table들을 쓰게 하려고 ddl-auto:update를 썼습니다.

2022-01-06 03:48 UTC, koseyeon commented on src/main/resources/application.yml
> +        format_sql: true
쿼리로 db를 찌를 때마다 어떤 쿼리가 들어가고 있는지 로그로 확인하기 위해서 show-sql:true를 썼고,
이 떄 hibernate의 옵션 중에서 format_sql:true를 해주면 로그에 출력되는 쿼리가 사람이 보기 편하게, 이쁘게 나온다고 하여 사용하였습니다. 참고 블로그 -> https://lannstark.tistory.com/14

2022-01-06 03:53 UTC, koseyeon commented
> 설정 파일을 수정하느라 고생했습니다!
> 
> 혹시 이 부분이 실제로 동작하는지 확인을 해봤는지 알고 싶습니다.
> 네 서버를 띄운다음에 mysql workbench로 DB에 테이블(answer,post 등)들이 잘 생성되었음을 확인했습니다.  
> 또 MySql은 어떤 방식으로 띄울것인지에 대한 부분도 설명이 추가되었으면 좋겠습니다!
mysql:latest 도커 이미지를 떙겨와서 컨테이너로 띄운 상태입니다.

2022-01-07 01:14 UTC, wannte commented on src/main/resources/application.yml
> +    password: ${PASSWORD}
좋은 방법 같습니다! 공개되면 안되는 정보에 관해서는 ec2에 정보를 담아두고 이를 사용하는 방식으로 진행하면 좋을 것 같네요!

이 방식을 적용하기 위해서는 `dev-develop.sh`부분도 결국 수정을 진행해야겠군요!

이러한 공개되면 안되는 환경변수들도 버전관리가 되면 더 좋겠네요! 이 부분은 추후에 고민해봅시다.

2022-01-07 01:16 UTC, wannte commented on src/main/resources/application.yml
> +      ddl-auto: update
hibernate를 통해, 우리가 정의한 Entity에 맞는 테이블 스키마를 작성하는 것은 매우 좋다고 생각합니다!

그렇다면, local, dev, prod 서버에 각각 어떤 ddl-auto 옵션을 쓰는 것이 좋을까요? 생각이 궁금합니다!

2022-01-07 01:20 UTC, wannte commented on src/main/resources/application.yml
> +        format_sql: true
친절한 설명 감사합니다!

한 가지 catch-up했으면 하는 부분은, 이 로그를 어떻게, 언제 볼 수 있는지에 대해서입니다!
local이나 test의 경우에는 바로 터미널에서 확인할 수 있는 반면에 dev서버에서는 쉽지 않을 것으로 보이는데요! 현재는 지금의 방식을 유지하고, 이후에 로그 정책을 도입할 때 함께 고민해봅시다!

2022-01-07 01:27 UTC, wannte reviewed
서버가 조금의 부하에도 뻗어버리기 때문에 하루 빨리 더 좋은 서버로 이전을 진행해야 할 것 같네요..
 
 커멘트 하나 추가했습니다 확인부탁드려요!

2022-01-07 01:27 UTC, wannte commented on src/main/resources/application.yml
> +    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
지금와서 확인한 부분인데요!

<img width="638" alt="Screen Shot 2022-01-07 at 10 21 58 AM" src="https://user-images.githubusercontent.com/49307266/148475858-095f80e5-1ed3-4a05-90ee-641aa3e480e4.png">


docker의 `mysql:latest`를 사용했을 때, MySQL 8버전을 pull하게 됩니다!

그러한 측면에서, 특정버전의 mysql을 pull 떙기는 게 더 좋지 않을까 제안 해봅니다! 어떤 버전의 mysql을 사용하는 것이 좋을지에 대해서도 한 번 고민해봐도 좋을 것 같네요!

또한, dockerfile을 만들어서 dev 서버의 database의 정보 또한 함께 버전관리가 된다면, 이후에 우리 프로젝트의 dev서버를 이전하게 되었을 때, history를 뒤져가며 docker 명령어를 찾지 않아도 될것 같네요!

2022-01-07 11:41 UTC, koseyeon commented on src/main/resources/application.yml
> +      ddl-auto: update
local은 create or update (로컬db는 갈아엎어도 문제 없다 생각)
dev는 update 또는 validate (dev db는 컬럼 삭제 등등을 가능하게 해서 빠른 개발이 가능하게 하는게 좋다고 생각)
prod는 validate 또는 none ( 운영 db는 최대한 건들지 말아야 한다고 생각)
을 쓰는게 좋을 것 같다고 생각합니다ㅎㅎ

2022-01-07 11:42 UTC, koseyeon commented on src/main/resources/application.yml
> +        format_sql: true
옙 좋습니다!

2022-01-08 07:04 UTC, koseyeon commented on src/main/resources/application.yml
> +    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
넵 도커파일을 만들어보도록 하겠습니다 좋은의견 감사합니다!

2022-01-08 11:59 UTC, koseyeon commented
배포 서버 안에 application-dev.yml 파일을 만들어 두어서 CD 진행시에 이 yml 파일을 profile로 사용하도록 했습니다.( 이를 위해 deploy.sh 스크립트를 수정하였습니다.)

2022-01-09 13:07 UTC, wannte approved these changes
이 부분만 진행되면 좋겠습니다.

서버 부분은 직접 만나서 확인했습니다!

2022-01-09 13:07 UTC, wannte commented on src/main/resources/application.yml
>    protocol: http
```suggestion
```

이 부분은 삭제를 진행하고, dev 서버에서 관리해도 좋을 것 같아요

2022-01-09 13:15 UTC, merged