Feat: CustomException 을 계층화한다
GIST-Petition-Site-Project/GIST-petition-server pull request #99
Opened 2022-01-06 13:21 UTC by GuruneLee

post 도메인에서 던지는 예외를 모두 클래스화 하였습니다.
부모 class 로 'PostException' 을 두고 이를 상속하여 구현하였습니다.

메시지와 http code를 미리 정의해 두는 것에 의의가 있는 것 같습니다.

문제점은 다음과 같습니다.
1. post 도메인에서 뱉는다고 꼭 PostException 의 자식으로 하면 어색한 부분이 있습니다. (ex. NonExistentUser)
2. 각 도메인이 뱉는 '상황'을 기준으로 하면, 재사용성이 떨어집니다 (ex. creatAnswer 메서드를 호출할 시, post가 없어 실패하면 CanNotCreateAnswer 예외를 뱉어야 합니까? 아니면 NonExistentPost 예외를 뱉어야 합니깝숑?)

첫 커밋은 코드 자체보단 아이디어를 나누고 싶습니다.

Close #75

2022-01-06 14:22 UTC, wannte reviewed
빠르게 진행해주셨네요!
간단하게 몇가지 질문 남기고 갑니다! 요 부분에 대해서만, 답변 진행해주시고 이어서 진행해도 좋을 것 같아요!

2022-01-06 14:22 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/exception/ControllerAdvice.java
> +    @ExceptionHandler(PostException.class)
도메인 별로 별도의 ExceptionHandler를 작성해주어야 할거 같은데요!

해당 도메인 Exception들의 부모클래스를 두고, 하나로 처리하는 방법은 어떨까요?

도메인이 추가될 수록, ExceptionHandler가 추가되는 부분은 불편할 수 있겠다는 생각입니다!

2022-01-06 14:22 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/exception/post/PostException.java
> +public class PostException extends RuntimeException {
도메인 별로 Exception을 분리하게 되었을 때 어떤 장점을 가질 수 있을까요?
또 User가 존재하는지에 대한 테스트를 거의 대부분의 서비스에서 진행하게 될거 같은데, 각 도메인 별로 별도로 정의해주는 부분은 비효율적일수도 있겠다는 생각인데요! 이부분의 생각도 궁금합니다!

이러한 공통적인 부분은 common 정도의 패키지에 묶어서 관리할 수도 있겠네요!

2022-01-06 14:22 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/exception/post/DuplicatedAgreementException.java
> +    public DuplicatedAgreementException() {
공백 또한 컨벤션이니 한줄 띄어주심이!

2022-01-06 14:26 UTC, wannte commented
PR의 내용을 뒤늦게 확인했네요!

1번에 대한 제 답은 위의 질문으로 대체할 수 있을거라 생각하고,
2번에 경우에는 상황보다도, 에러의 원인에 더 집중하면 좋을 거 같다는 게 제 생각입니다. 하나의 원인이 발생할 수 있는 상황은 다양하지만, 에러는 하나기 때문지요

2022-01-07 06:05 UTC, GuruneLee commented on src/main/java/com/example/gistcompetitioncnserver/exception/ControllerAdvice.java
> +    @ExceptionHandler(PostException.class)
네 저도 루트 예외를 하나 두는것을 염두해두고 있었습니다

2022-01-07 10:16 UTC, ChoiEungi reviewed
domain 별로 문서화까지 너무 고생하셨습니다! notion의 내용을 wiki로 옮겨도 좋을 것 같습니다!

2022-01-09 12:02 UTC, koseyeon commented on src/main/java/com/example/gistcompetitioncnserver/exception/CustomException.java
> +        this.httpStatus = httpStatus;
다른 exception들은 다 분류를 하셨는데 (postException 등) ,
이메일익셉션, 파일익셉션들은 분류를 따로 안하고 customException으로 남기신 이유가 궁금합니다!

2022-01-09 12:02 UTC, koseyeon commented on src/main/java/com/example/gistcompetitioncnserver/exception/CustomException.java
> +    public CustomException(String message, Throwable cause, HttpStatus httpStatus) {
다른 exception들은 다 분류를 하셨는데 (postException 등) ,
이메일익셉션, 파일익셉션들은 분류를 따로 안하고 customException으로 남기신 이유가 궁금합니다!

2022-01-09 15:39 UTC, wannte requested changes
Exception을 상세하게 나누고 처리하니 가독성이 훨씬 좋아진 것 같네요!

테스트에서 또한, CustomExcption이 발생한다의 검증보다도 구체적인 에러 검증을 진행할 수 있었던 것 같습니다 :+1:

한 가지, CustomException과 ApplicationException의 동시 사용에 관한 피드백을 남겼으니 확인 부탁드려요!

2022-01-09 15:39 UTC, wannte commented on src/test/java/com/example/gistcompetitioncnserver/answer/AnswerServiceTest.java
> +        ).isInstanceOf(UnAnsweredPostException.class);
테스트 메소드 명을 수정했으면 좋겠습니다!
제안: retrieveAnswerFromNotAnsweredPost()
Answer되지 않은 경우인데, 이 부분이 들어나지 않아 헷갈렸네요!(근데 아마 이거 내가 바꾼거 같기도 하고..)

밑에 메소드 명 중  `Exitent`의 명사형 보다는 `Existing`의 형용사를 쓰는 것 또한 제한 해봅니다!

2022-01-09 15:39 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/answer/AnswerController.java
> +
공백 또한 컨벤션!

2022-01-09 15:39 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/answer/AnswerController.java
> +
공백 또한 컨벤션 2

2022-01-09 15:39 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/comment/CommentService.java
> +
공백33

2022-01-09 15:39 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/exception/CustomException.java
> +    public CustomException(String message, Throwable cause, HttpStatus httpStatus) {
CustomException과 ApplicationException의 기준이 조금 더 명확했으면 좋겠다는 생각입니다! (클래스 명에서 그 역할이 명시적으로 들어났으면 합니다)

CustomExcepion -> 우리가 커스텀하게 정의한 Exception
ApplicationException -> 어플리케이션을 동작시키는 데 발생하는 Exception

요 정도로 그 이름만을 봤을 떄 유추할 수 있을 것 같아요!

이러한 관점에서 보면 이메일익셉션과 파일익센션도 모두 CustomException, ApplicationException에 포함되도 어색하지 않을 것 같다는 생각입니다.

CustomException과 ApplicationException을 동시에 두었을 때 어떠한 장점을 가질 수 있는지에 대한 생각을 들어보고 싶습니다!

2022-01-09 15:39 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/exception/comment/NoSuchCommentException.java
> +    private static final HttpStatus HTTP_STATUS = null;
이 부분은 내일 하나씩 보면서 결정해도 좋겠네요!

2022-01-09 15:39 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/user/UserRole.java
> +            throw new CustomException("존재하지 않는 유저 권한입니다.", e);
이 부분을 CustomException으로 정의한 이유가 궁금합니다!

2022-01-09 15:39 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/verification/VerificationService.java
> +                .orElseThrow(() -> new CustomException("존재하지 않는 토큰입니다.", null));
이 부분도 마찬가지구요!

2022-01-10 15:14 UTC, wannte approved these changes
여러가지로 세세하게 고민할 부분이 많았던 기능이였을 거 같은데, 깔끔하게 진행해주셨네요!

몇 가지 코멘트 남겼고, 위의 코멘트 들도 확인 부탁드립니다! 리뷰는 제안일 뿐, 어떤 방법을 선택할 지는 알아서 선택해주시고 머지 진행해주시면 감사하겠습니다. 가능하면 내일 오전 중으로 진행해주셔야, 다음 feature 진행할 수 있을 것 같습니다.

어떤 결정을 내렸는지에 대한 이유나 근거를 리뷰로 남겨주시면 감사하겠습니다 👍

2022-01-10 15:14 UTC, wannte commented on src/main/java/com/example/gistcompetitioncnserver/exception/user/NoSessionException.java
> +    private static final String MESSAGE = "세션유저가 존재하지 않습니다.";
'세션'을 사용하는 부분을 사용자에게 노출할 필요성이 있을까? 에 대한 고민이 남네요

UnAuthenticatedExeption, "인증되지 않은 사용자입니다" 정도의 클래스명과 메시지를 제안해봅니다.

2022-01-10 15:14 UTC, wannte commented on src/test/java/com/example/gistcompetitioncnserver/answer/AnswerServiceTest.java
> +        Answer answer = answerRepository.findById(savedAnswer).orElseThrow(() -> new WrappedException("존재하지 않는 answer입니다.", null));
이 부분에서 WrappedException을 사용하는 이유가 궁금합니다.

2022-01-11 05:01 UTC, GuruneLee commented on src/main/java/com/example/gistcompetitioncnserver/exception/user/NoSessionException.java
> +    private static final String MESSAGE = "세션유저가 존재하지 않습니다.";
UnAuthenticatedExeption, "인증되지 않은 사용자입니다" 로 바꾸는데 찬성합니다.

이를 어떻게 전달할지는 다음 이슈에서 생각해보면 좋을 것 같습니다.

2022-01-11 05:02 UTC, GuruneLee commented on src/test/java/com/example/gistcompetitioncnserver/answer/AnswerServiceTest.java
> +        Answer answer = answerRepository.findById(savedAnswer).orElseThrow(() -> new WrappedException("존재하지 않는 answer입니다.", null));
answer 는 post 종속적이라 answer exception 을 따로 분리하지 않았습니다. (그럴 필요도 없었습니다)
그래서 테스트 메서드에서만 사용할 목적으로 exception 을 만드는 것이 낭비라 판단했습니다.

2022-01-11 05:03 UTC, merged